### ISSUE TITLE
Nice name

### ISSUE THREAD

**Issue by BSchilperoort** [EcoExtreML/zampy#1]
We will of course want a nice name for the package :)

**Comment by SarahAlidoost** [comment]
Hi @EcoExtreML/developers and @EcoExtreML/maintainers, in this issue, we are collecting suggestions for a good name for our Python package. See [here](https://github.com/EcoExtreML/lsmdata#readme) for more info about the package. Do you have ideas and suggestions about the name? then please write them in this issue.

**Comment by BSchilperoort** [comment]
Do note that we would like a simple name, [following python conventions](https://peps.python.org/pep-0008/#package-and-module-names). 
> Python packages should also have short, all-lowercase names, although the use of underscores is discouraged.

For example:
- numpy
- [s2spy](https://github.com/AI4S2S/s2spy)
- [lilio](https://github.com/AI4S2S/lilio)

The name should also still be available on [PyPI](https://pypi.org/)

**Comment by BSchilperoort** [comment]
Ideas/inspiration:

- `mauro`, after the [Fra Mauro map](https://en.wikipedia.org/wiki/Fra_Mauro_map). "considered the greatest memorial of medieval cartography."
- `draca`, after the gold-hoarding dragon from [Beowulf](https://en.wikipedia.org/wiki/The_dragon_(Beowulf)).

**Comment by yijianzeng** [comment]
hi Bart, Sarah, what about simply using 'ecoextreml'?

**Comment by SarahAlidoost** [comment]
Ideas:
- parseo: parse EO
- zampy: zam is the [Avestan language](https://en.wikipedia.org/wiki/Avestan_language) term for the [Zoroastrian](https://en.wikipedia.org/wiki/Zoroastrianism) concept of "earth", in both the sense of land and soil and in the sense of the world.

**Comment by SarahAlidoost** [comment]
> hi Bart, Sarah, what about simply using 'ecoextreml'? If you think stemmusscope is too long a package name.

Here we are looking for a unique and simple name (see [Bart comment](https://github.com/EcoExtreML/lsmdata/issues/1#issuecomment-1505117670)) because we are developing a (generic) python package "to download and reformat input data that are commonly used by land surface models", see [my comment](https://github.com/EcoExtreML/lsmdata/issues/1#issuecomment-1504928029). The package will be eventually re-used in other projects. `ecoextreml` is the name of our project and `stemmusscope` is the name of the model. These names already exist and are used for other purposes.

**Comment by geek-yang** [comment]
😂 This issue actually teaches me many new things that I don't even have a clue. Thanks @BSchilperoort @SarahAlidoost.

Sorry for my poor vocabulary capacity (for fancy words), only some boring names came into my mind:

- `trailblazer`: well...land...surface...we are the first, hmmm...seem to make sense
- `rover`: search something on the land...hmmm...

**Comment by BSchilperoort** [comment]
Those are sadly already claimed on pypi, @geek-yang 

> Ideas:
>     * `parseo`: parse EO
>     * `zampy`: zam is the [Avestan language](https://en.wikipedia.org/wiki/Avestan_language) term for the [Zoroastrian](https://en.wikipedia.org/wiki/Zoroastrianism) concept of "earth", in both the sense of land and soil and in the sense of the world.

Those are both nice and available! I think my first choice is now `zampy` :smile:

**Comment by bobzsu** [comment]
I think it can be better called gaia - meaning 'get all input aligned', gaia is also thought the mother earth. not sure if it is used already, other gaia-dte or gaia-eo. all your suggestions are fine but it hard to guess what they may mean.
