### ISSUE TITLE
File size check before downloading via `cdsapi`

### ISSUE THREAD

**Issue by geek-yang** [EcoExtreML/zampy#12]
For the data downloading request via CDS, currently we only check the existence via file name, e.g.:

https://github.com/EcoExtreML/zampy/blob/cf04f55e97a7c9e47d4cb1b88e6610e006b91c2f/src/zampy/datasets/utils.py#L107-L109

It is better to verify the size rather than only the file name. However, it seems there is no way to simply request the url and check the size before downloading. We can only start retrieve data and then get the size, for instance:

```py
import cdsapi
c = cdsapi.Client()
r = c.retrieve(...) # make a request and start the downloading process
r.content_length # bytes
>>> 65337064
```

Just wonder if there is a way to request more info (size) before downloading?

Otherwise, if there is a way to terminate the download and cancel the request with python client, that's also fine. But from the [documentation](https://confluence.ecmwf.int/display/UDOC/How+to+cancel+a+request+-+Web+API+FAQ) and the [source code](https://github.com/ecmwf/cdsapi/blob/master/cdsapi/api.py), it seems this is only possible via web api, not via `cdsapi`.

Any idea?

**Comment by BSchilperoort** [comment]
Hi Yang, I just had a look, and your example actually works. Note that `.retrieve` only retrieves the info, not the file itself!

`r.content_length` will return the size of the file in bytes. This can be compared to `Path(...).stat().st_size`.

**Comment by geek-yang** [comment]
> Hi Yang, I just had a look, and your example actually works. Note that `.retrieve` only retrieves the info, not the file itself!
> 
> `r.content_length` will return the size of the file in bytes. This can be compared to `Path(...).stat().st_size`.

I think when we call `.retrieve`, it raises a downloading request to the server and it starts queuing. Then we can get `r.content_length`. But if we don't cancel the request via webapi, the downloading will start later.

If there is a way for us to cancel the request via python client, then this will work.

**Comment by geek-yang** [comment]
> I would expect `r.delete()` to cancel the request 🤔
> 
> Edit: no, it does not...

Yep.....I checked the source code of `cdsapi`.....it seems they didn't provide any handle for this. It is super strange that you can only cancel it via web api. I plan to raise an issue in their repo.

**Comment by BSchilperoort** [comment]
But does it actually matter (to us) if we call `retrieve`, which prepares the request, and then not download it? I don't think there is anything to cancel anymore: the file is already ready for download on their server.

We can then decide to just not download it. This is mostly just a waste of their compute/memory.

Ideally they should also provide a checksum for the file, which would allow for validating that the transfer went correctly.
