### ISSUE TITLE
ERA5 download is skipping the end year

### ISSUE THREAD

**Issue by BSchilperoort** [EcoExtreML/zampy#17]
Trying download(start=2020, end=2020) results in no data being downloaded.
download(start=2019, end=2020) will only download 2019.

**Comment by geek-yang** [comment]
This is because I assume that the input for time bounds should be `TimeBounds(np.datetime64("2020-01-01"), np.datetime64("2020-12-31"))` if you want to download data for 2020. But I agree that we should support `download(start=2020, end=2020)` this. I would fix it in another PR.

**Comment by BSchilperoort** [comment]
Hm yeah. I have changed the recipe manager so it turns `years: [2020, 2020]` into `TimeBounds(np.datetime64("2020-01-01"), np.datetime64("2020-12-31"))`. That fixed it :+1:
