### ISSUE TITLE
Zampy not working in Utwente CRIB.

### ISSUE THREAD

**Issue by prajzwal08** [EcoExtreML/zampy#33]
Working on Zampy on own device works well, while installing zampy on CRIB faces error. 
ERROR: No matching distribution found for zampy.

**Comment by geek-yang** [comment]
Did you try to install it via `pip install zampy`? Currently `zampy` is still under development and we haven't made a stable release of it. That is planned and we will have it soon.

If you want to give a try, then you need to clone the repo and install it via the following command (development mode):
```py
cd zampy/
pip install -e .
```

There are some functionalities in place. But I would recommend to wait a bit and use it when we make the stable release. Thanks for trying.

**Comment by SarahAlidoost** [comment]
@prajzwal08 great to see you here, thanks for submitting the issue :sunglasses:. In addition to Yang's comment, see the other considerations:
1- If you want to install something on CRIB via pip, please use `pip install --user <name of package>` for example for installing zampy from github,` !pip install --user git+https://github.com/EcoExtreML/zampy`, see[ this issue](https://github.com/EcoExtreML/STEMMUS_SCOPE_Processing/issues/81).
2- The python version on CRIB is `3.8`, but zampy works with `python >=3.9`. So, the zampy cannot be installed there unless you create a different environment (jupyter kernel on CRIB) with the newest version. For creating a jupyter kernel on CRIB, please contact Serkan or CRIB administrator.  

I suggest installing zampy on your own laptop or on SURF Snellius. If you encounter any other problems, please don't hesitate to submit it as an issue or report it here. :+1:
