### ISSUE TITLE
Missing Registration for Soil Moisture Data in 'src/zampy/reference/variables.py'

### ISSUE THREAD

**Issue by prajzwal08** [EcoExtreML/zampy#47]
Hello,

I noticed that in the file "src/zampy/reference/variables.py," there is no registration for Soil Temperature levels 1 to 4 and Volumetric Soil Water layers 1 to 4. These variables are needed to roundabout the model warm up problem. We have faced problems when downloading those data from ERA5 land using a command line recipe. And i feel this might be the problem. Does adding variables in that script enable us to download them? 

Best regards,
Prajwal

**Comment by BSchilperoort** [comment]
Hi Prajwal,

I can add the ERA5-land variables. I'll have to add them to the variable reference and the [ERA5-land code](https://github.com/EcoExtreML/zampy/blob/7ad91da3dcb18ebdbd3b0dc4508189ed1accfeed/src/zampy/datasets/era5.py#L43).
