### ISSUE TITLE
example recipe for downloading global data for running STEMMUS-SCOPE

### ISSUE THREAD

**Issue by yijianzeng** [EcoExtreML/zampy#54]
Hi, we cannot find an exact 'example recipe' for downloading global data for running STEMMUS-SCOPE. We understand as long as we use zampy to download data with the following folder structure: 
![image](https://github.com/EcoExtreML/zampy/assets/10754705/2eadbd99-6dfe-4279-8026-21dc75efae50)
we then can use PyStemmusScope to process the global data and run the STEMMUS-SCOPE. If there is an 'example recipe' specifically provided for downloading global data for STEMMUS-SCOPE as shown in the above figure, it would be great.

**Comment by BSchilperoort** [comment]
I am running a recipe that should do this right now (testing it on my machine), but the CDS (where we download most of our data from) is migrating to a new system and therefore barely available: https://confluence.ecmwf.int/display/CUSF/A+new+CDS+soon+to+be+launched+-+expect+some+disruptions

**Comment by yijianzeng** [comment]
@BSchilperoort Hi Bart, with the new forum, i found the below statement:

> To help alleviate the longer than normal waiting times, a decision has been made to implement a temporary measure from now on until the use of the new data infrastructure is fully optimised. All data requests asking for hourly data with the period of more than one month will be set with lower priorities in the queue, which means other requests will get executed earlier. If the CDS is affected heavily by such long period data requests, we will remove such requests from the queue. If this happens, please resubmit your requests with reduced period (one month) afterwards.

As such, let's download example data for two weeks or so, which could be scaled up when the new CDS is updated. What do you think?

**Comment by SarahAlidoost** [comment]
an example recipe is now available https://github.com/EcoExtreML/zampy/blob/main/recipes/STEMMUS_SCOPE_input.yml
