### ISSUE TITLE
Move to new CDS and ADS

### ISSUE THREAD

**Issue by BSchilperoort** [EcoExtreML/zampy#59]
see https://forum.ecmwf.int/t/the-new-climate-data-store-beta-cds-beta-is-now-live/3315

Old CDS will be shut down 3 September 2024. The new grib -> netCDF converter that they use at the beta-cds is also still experimental and might change in the future. This will be difficult to support :/

**Comment by SarahAlidoost** [comment]
also see [New Coordinate variable names](https://confluence.ecmwf.int/display/CKB/GRIB+to+netCDF+conversion+on+new+CDS+and+ADS+systems#GRIBtonetCDFconversiononnewCDSandADSsystems-NewCoordinatevariablenames) in netcdf conversion.
